public class Resources {
    public static String instructions = "<html>" 
                    + "Instructions: " + "<br>"
                    + "1. Connect both devices to the same LAN." + "<br>"
                    + "2. Click the 'Receive' button on the receiving device." + "<br>"
                    + "3. Click the 'Send' button on the transmitting device." + "<br>"
                    + "4. Select the IP address of the receiving device from the list." + "<br>"
                    + "5. Choose file/files to send." + "<br>"
                    + "6. Wait until the operation is completed." + "<br>"
                    + "<br>"
                    + "<br>"
                    + "Setting your network adapter to use the 5GHz band can dramatically improve the transfer speed." + "<br>"
                    + "Refer to the following link on how to set up the 5GHz band on your Windows device." + "<br>"
                    + "<br>"
                    + "<a href=\"https://mcgillqa.service-now.com/itportal?id=kb_article_view&sysparm_article=KB0012126&sys_kb_id=a6cfa57fdb5bb410701f5a6a689619ea&spa=1\">"
                    + "https://mcgillqa.service-now.com/itportal?id=kb_article_view&sysparm_article=KB0012126&sys_kb_id=a6cfa57fdb5bb410701f5a6a689619ea&spa=1"
                    + "</a>"
                    + "<br>"
                    + "<br>"
                    + "Using mobile hotspot can also speed things up since then a router won't be a bottleneck."
                    + "</html>";
}
